# DEFINE YOUR UNIQUE PARAMETER VALUES HERE.
KUBECTL := microk8s.kubectl
WORK_DIR := ./src-kubernetes/
DJANGO_WORK_DIR := ./core/

.PHONY: DEPLOY-PROMETHEUS
DEPLOY-PROMETHEUS:
	@echo "ENABLING OBSERVABILITY ADDON FOR THIS MICROK8S CLUSTER..."
	microk8s enable prometheus


.PHONY: DEPLOY-SQUADLIST-LOCALLY
DEPLOY-SQUADLIST-LOCALLY:
	@echo "RUNNING THE DJANGO EPL API APPLICATION DIRECTLY FROM THE DJANGO WEB SERVER.."
	python3 $(DJANGO_WORK_DIR)manage.py runserver 0.0.0.0:4444

.PHONY: DEPLOY-SQUADLIST-K8s
DEPLOY-SQUADLIST-K8s:
	@echo "DEPLOYING THE EPL API APPLICATION FROM THE MICROK8S CLUSTER"
	$(KUBECTL) apply -f $(WORK_DIR)templates/namespace.yaml
	$(KUBECTL) apply -f $(WORK_DIR)templates/deployment.yaml
	

.PHONY: PORT-FORWARD-SQUADLIST-K8s
PORT-FORWARD-SQUADLIST-K8s:
	@echo "PORT FORWARDING THE DEPLOYMENT APP TO VIEW ON A WEB BROWSER.."
	$(KUBECTL) port-forward deployment/djangoeplsquadlist :4444 -n djangoeplsquadlist
	
