# Generated by Django 4.2.7 on 2024-01-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EPL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position', models.CharField(max_length=250)),
                ('Nation', models.CharField(choices=[('Arsenal', 'Arsenal'), ('AstonVilla', 'Astonvilla'), ('Bournemouth', 'Bournemouth'), ('Brentford', 'Brentford'), ('Brighton', 'Brighton'), ('Burnley', 'Burnley'), ('Chelsea', 'Chelsea'), ('CrystalPalace', 'Crystalpalace'), ('Everton', 'Everton'), ('Fulham', 'Fulham'), ('Liverpool', 'Liverpool'), ('Luton', 'Luton'), ('ManchesterCity', 'Manchestercity'), ('NewcastleUnited', 'Newcastleunited'), ('NottinghamForest', 'Nottinghamforest'), ('ShieffieldUnited', 'Shieffieldunited'), ('TottenhamHotSpur', 'Tottenhamhotspur'), ('Westham', 'Westham'), ('Wolves', 'Wolves')], max_length=250)),
                ('Team', models.CharField(max_length=250)),
                ('PlayerName', models.CharField(max_length=250)),
            ],
        ),
    ]
