# Generated by Django 4.2.7 on 2024-01-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eplsquadlist', '0002_alter_epl_nation_alter_epl_playername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epl',
            name='Nation',
            field=models.CharField(choices=[('Arsenal', 'Arsenal'), ('AstonVilla', 'Astonvilla'), ('Bournemouth', 'Bournemouth'), ('Brentford', 'Brentford'), ('Brighton', 'Brighton'), ('Burnley', 'Burnley'), ('Chelsea', 'Chelsea'), ('CrystalPalace', 'Crystalpalace'), ('Everton', 'Everton'), ('Fulham', 'Fulham'), ('Liverpool', 'Liverpool'), ('Luton', 'Luton'), ('ManchesterCity', 'Manchestercity'), ('NewcastleUnited', 'Newcastleunited'), ('NottinghamForest', 'Nottinghamforest'), ('ShieffieldUnited', 'Shieffieldunited'), ('TottenhamHotSpur', 'Tottenhamhotspur'), ('Westham', 'Westham'), ('Wolves', 'Wolves')], max_length=256),
        ),
        migrations.AlterField(
            model_name='epl',
            name='PlayerName',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='epl',
            name='Position',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='epl',
            name='Team',
            field=models.CharField(max_length=256),
        ),
    ]
